### ISSUE TITLE
backupEtcd.sh error: manifest for ibmcom/etcd:v3.2.24 not found.

### ISSUE THREAD

**Issue by lissettegar** [ibm-cloud-architecture/icp-backup#21]
Hi,
There is an error running backupEtcd.sh script:

[root@icp-master1 scripts]# ./backupEtcd.sh
Current Time : 2019.03.04-10.27.26
Back up to the following file:  /data/etcd.2019.03.04-10.27.26.db
Unable to find image 'ibmcom/etcd:v3.2.24' locally
docker: Error response from daemon: manifest for ibmcom/etcd:v3.2.24 not found.
See 'docker run --help'.

Loocking at the etcd.sh script you can see that the Tag is defined as "v3.2.24", but the actual Tag is "3.2.4" whitout the "v". If you change the Tag definition in the script, the script works ok and the snapshot is created.

Thanks for your time, Lissette

**Comment by patrocinio** [comment]
Problem fixed:

eduardos-air:scripts edu$ ./backupEtcd.sh 
Current Time : 2019.05.21-13.03.13
Back up to the following file:  /data/etcd.2019.05.21-13.03.13.db
Unable to find image 'ibmcom/etcd:3.2.24' locally
3.2.24: Pulling from ibmcom/etcd
8c5a7da1afbc: Pull complete 
0d363128e48e: Pull complete 
1ba5e77f0f6e: Pull complete 
Digest: sha256:6bdd5aaa912504d7c346c61d61b2c015cbb10e81b6ed5a73a0dfd3fae6f9668f
Status: Downloaded newer image for ibmcom/etcd:3.2.24
