### ISSUE TITLE
In ICP 3.1.1 maria db pod is not getting started

### ISSUE THREAD

**Issue by ramakila** [ibm-cloud-architecture/icp-backup#23]
Hi,

ICP dash board is down with 504 gateway timeout error and in the master node noticed maria db pod is not started because /var/lib/mysql got overwrote by other process. Is there any way I can create maria db pod from initial ICP installation or any other way to recover.  We don't have much work happened after ICP installation, we are ok to restore with initial one.

**Comment by patrocinio** [comment]
Hello @ramakila 
Did you do any backup/restore procedure?
I am wondering how to MySQL database got corrupted...
Thanks
