### ISSUE TITLE
etcd restore not working on icp3.1.1

### ISSUE THREAD

**Issue by roitevethibm** [ibm-cloud-architecture/icp-backup#24]
Etcd won't start after restoring in ICP3.1.1,
I found that at this icp version etcd is configured with dedicated wal directory(--wal-dir=/var/lib/etcd-wal) the etcd snapshot restore puts both the wal and snap files in the same directory(/var/lib/etcd) so etcd starting with the old wal files and crashing. my solution is to move the restored wal files from /var/lib/etcd/member/wal to /var/lib/etcd-wal/wal 
I made a fork to this repository with my fixes at https://github.com/roitevethibm/icp-backup/blob/master/docs/etcd_restore_multi.md 
can you please validate it? if my solution gets validated I'll be glad to make a pull request from my fork.

Thank you
Roi Teveth

**Comment by patrocinio** [comment]
Hello Roi,

    Thanks for your work.
     Your solution looks good.
      Can you please create a PR?

    Thanks,

Eduardo

**Comment by roitevethibm** [comment]
Thank you for your attention.
i created PR with 3 commits
https://github.com/ibm-cloud-architecture/icp-backup/pull/25
